language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t aniketpatel/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true aniketpatel/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-016293920362"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
